apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crafteo-whoami
spec:
  dnsNames:
  - "*.devops.crafteo.io"
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  secretName: crafteo-whoami-certificate