apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-acme-issuer
  namespace: cert-manager
spec:
  acme:
    email: pierre@crafteo.io
    privateKeySecretRef:
      name: cert-manager-acme-private-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          accessKeyID: AKIAQE5MM2AXHYV4H6GZ
          region: eu-west-3
          secretAccessKeySecretRef:
            key: secret-access-key
            name: cert-manager-aws-secret
